import { defineConfig } from 'vitepress'

const sidebar = {
  prologue: [
    { text: 'Release Notes', link: '/releases' },
    { text: 'Upgrade Guide', link: '/upgrade' },
    { text: 'Contribution Guide', link: '/contributions' },
  ],
  gettingStarted: [
    { text: 'Installation', link: '/installation' },
    { text: 'Configuration', link: '/configuration' },
    { text: 'Directory Structure', link: '/structure' },
    { text: 'Frontend', link: '/frontend' },
    { text: 'Starter Kits', link: '/starter-kits' },
    { text: 'Deployment', link: '/deployment' },
  ],
  architecture: [
    { text: 'Request Lifecycle', link: '/lifecycle' },
    { text: 'Service Container', link: '/container' },
    { text: 'Service Providers', link: '/providers' },
    { text: 'Facades', link: '/facades' },
    { text: 'Contracts', link: '/contracts' },
  ],
  basics: [
    { text: 'Routing', link: '/routing' },
    { text: 'Middleware', link: '/middleware' },
    { text: 'CSRF Protection', link: '/csrf' },
    { text: 'Controllers', link: '/controllers' },
    { text: 'Requests', link: '/requests' },
    { text: 'Responses', link: '/responses' },
    { text: 'Views', link: '/views' },
    { text: 'Blade Templates', link: '/blade' },
    { text: 'Asset Bundling (Vite)', link: '/vite' },
    { text: 'Validation', link: '/validation' },
    { text: 'Error Handling', link: '/errors' },
    { text: 'Logging', link: '/logging' },
    { text: 'Session', link: '/session' },
  ],
  diggingDeeper: [
    { text: 'Artisan Console', link: '/artisan' },
    { text: 'Broadcasting', link: '/broadcasting' },
    { text: 'Cache', link: '/cache' },
    { text: 'Collections', link: '/collections' },
    { text: 'Concurrency', link: '/concurrency' },
    { text: 'Context', link: '/context' },
    { text: 'Events', link: '/events' },
    { text: 'File Storage', link: '/filesystem' },
    { text: 'Helpers', link: '/helpers' },
    { text: 'HTTP Client', link: '/http-client' },
    { text: 'Images', link: '/images' },
    { text: 'Localization', link: '/localization' },
    { text: 'Mail', link: '/mail' },
    { text: 'Notifications', link: '/notifications' },
    { text: 'Package Development', link: '/packages' },
    { text: 'Processes', link: '/processes' },
    { text: 'Prompts', link: '/prompts' },
    { text: 'Queues', link: '/queues' },
    { text: 'Rate Limiting', link: '/rate-limiting' },
    { text: 'Task Scheduling', link: '/scheduling' },
    { text: 'Strings', link: '/strings' },
    { text: 'URL Generation', link: '/urls' },
    { text: 'Mix (Legacy)', link: '/mix' },
  ],
  security: [
    { text: 'Authentication', link: '/authentication' },
    { text: 'Authorization', link: '/authorization' },
    { text: 'Email Verification', link: '/verification' },
    { text: 'Encryption', link: '/encryption' },
    { text: 'Hashing', link: '/hashing' },
    { text: 'Password Reset', link: '/passwords' },
  ],
  database: [
    { text: 'Getting Started', link: '/database' },
    { text: 'Query Builder', link: '/queries' },
    { text: 'Pagination', link: '/pagination' },
    { text: 'Migrations', link: '/migrations' },
    { text: 'Seeding', link: '/seeding' },
    { text: 'Redis', link: '/redis' },
    { text: 'MongoDB', link: '/mongodb' },
  ],
  eloquent: [
    { text: 'Getting Started', link: '/eloquent' },
    { text: 'Relationships', link: '/eloquent-relationships' },
    { text: 'Collections', link: '/eloquent-collections' },
    { text: 'Mutators / Casts', link: '/eloquent-mutators' },
    { text: 'API Resources', link: '/eloquent-resources' },
    { text: 'Serialization', link: '/eloquent-serialization' },
    { text: 'Factories', link: '/eloquent-factories' },
  ],
  testing: [
    { text: 'Getting Started', link: '/testing' },
    { text: 'HTTP Tests', link: '/http-tests' },
    { text: 'Console Tests', link: '/console-tests' },
    { text: 'Database Testing', link: '/database-testing' },
    { text: 'Mocking', link: '/mocking' },
    { text: 'Dusk (Browser Tests)', link: '/dusk' },
  ],
  packages: [
    { text: 'Billing (Cashier)', link: '/billing' },
    { text: 'Cashier Paddle', link: '/cashier-paddle' },
    { text: 'Envoy', link: '/envoy' },
    { text: 'Fortify', link: '/fortify' },
    { text: 'Folio', link: '/folio' },
    { text: 'Homestead', link: '/homestead' },
    { text: 'Horizon', link: '/horizon' },
    { text: 'Octane', link: '/octane' },
    { text: 'Passport', link: '/passport' },
    { text: 'Pennant', link: '/pennant' },
    { text: 'Pint', link: '/pint' },
    { text: 'Precognition', link: '/precognition' },
    { text: 'Pulse', link: '/pulse' },
    { text: 'Reverb', link: '/reverb' },
    { text: 'Sail', link: '/sail' },
    { text: 'Sanctum', link: '/sanctum' },
    { text: 'Scout', link: '/scout' },
    { text: 'Socialite', link: '/socialite' },
    { text: 'Telescope', link: '/telescope' },
    { text: 'Valet', link: '/valet' },
  ],
  ai: [
    { text: 'AI', link: '/ai' },
    { text: 'AI SDK', link: '/ai-sdk' },
    { text: 'Boost', link: '/boost' },
    { text: 'MCP', link: '/mcp' },
  ],
}

function enSidebar() {
  return [
    { text: 'Prologue', items: sidebar.prologue },
    { text: 'Getting Started', items: sidebar.gettingStarted },
    { text: 'Architecture Concepts', items: sidebar.architecture },
    { text: 'The Basics', items: sidebar.basics },
    { text: 'Digging Deeper', items: sidebar.diggingDeeper },
    { text: 'Security', items: sidebar.security },
    { text: 'Database', items: sidebar.database },
    { text: 'Eloquent ORM', items: sidebar.eloquent },
    { text: 'Testing', items: sidebar.testing },
    { text: 'Official Packages', items: sidebar.packages },
    { text: 'AI / Ecosystem', items: sidebar.ai },
  ]
}

const zhSidebar = {
  prologue: [
    { text: '版本说明', link: '/releases' },
    { text: '升级指南', link: '/upgrade' },
    { text: '贡献指南', link: '/contributions' },
  ],
  gettingStarted: [
    { text: '安装', link: '/installation' },
    { text: '配置', link: '/configuration' },
    { text: '目录结构', link: '/structure' },
    { text: '前端', link: '/frontend' },
    { text: '入门套件', link: '/starter-kits' },
    { text: '部署', link: '/deployment' },
  ],
  architecture: [
    { text: '请求生命周期', link: '/lifecycle' },
    { text: '服务容器', link: '/container' },
    { text: '服务提供者', link: '/providers' },
    { text: 'Facades', link: '/facades' },
    { text: 'Contracts', link: '/contracts' },
  ],
  basics: [
    { text: '路由', link: '/routing' },
    { text: '中间件', link: '/middleware' },
    { text: 'CSRF 保护', link: '/csrf' },
    { text: '控制器', link: '/controllers' },
    { text: '请求', link: '/requests' },
    { text: '响应', link: '/responses' },
    { text: '视图', link: '/views' },
    { text: 'Blade 模板', link: '/blade' },
    { text: '资源构建 (Vite)', link: '/vite' },
    { text: '验证', link: '/validation' },
    { text: '错误处理', link: '/errors' },
    { text: '日志', link: '/logging' },
    { text: 'Session', link: '/session' },
  ],
  diggingDeeper: [
    { text: 'Artisan 控制台', link: '/artisan' },
    { text: '广播', link: '/broadcasting' },
    { text: '缓存', link: '/cache' },
    { text: '集合', link: '/collections' },
    { text: '并发', link: '/concurrency' },
    { text: '上下文', link: '/context' },
    { text: '事件', link: '/events' },
    { text: '文件存储', link: '/filesystem' },
    { text: '辅助函数', link: '/helpers' },
    { text: 'HTTP 客户端', link: '/http-client' },
    { text: '图片处理', link: '/images' },
    { text: '本地化', link: '/localization' },
    { text: '邮件', link: '/mail' },
    { text: '通知', link: '/notifications' },
    { text: '扩展包开发', link: '/packages' },
    { text: '进程', link: '/processes' },
    { text: 'Prompts', link: '/prompts' },
    { text: '队列', link: '/queues' },
    { text: '频率限制', link: '/rate-limiting' },
    { text: '任务调度', link: '/scheduling' },
    { text: '字符串', link: '/strings' },
    { text: 'URL 生成', link: '/urls' },
    { text: 'Mix (旧版)', link: '/mix' },
  ],
  security: [
    { text: '认证', link: '/authentication' },
    { text: '授权', link: '/authorization' },
    { text: '邮箱验证', link: '/verification' },
    { text: '加密', link: '/encryption' },
    { text: '哈希', link: '/hashing' },
    { text: '密码重置', link: '/passwords' },
  ],
  database: [
    { text: '快速入门', link: '/database' },
    { text: '查询构造器', link: '/queries' },
    { text: '分页', link: '/pagination' },
    { text: '数据迁移', link: '/migrations' },
    { text: '数据填充', link: '/seeding' },
    { text: 'Redis', link: '/redis' },
    { text: 'MongoDB', link: '/mongodb' },
  ],
  eloquent: [
    { text: '快速入门', link: '/eloquent' },
    { text: '关联关系', link: '/eloquent-relationships' },
    { text: '集合', link: '/eloquent-collections' },
    { text: '修改器 / 类型转换', link: '/eloquent-mutators' },
    { text: 'API 资源', link: '/eloquent-resources' },
    { text: '序列化', link: '/eloquent-serialization' },
    { text: '工厂', link: '/eloquent-factories' },
  ],
  testing: [
    { text: '快速入门', link: '/testing' },
    { text: 'HTTP 测试', link: '/http-tests' },
    { text: '控制台测试', link: '/console-tests' },
    { text: '数据库测试', link: '/database-testing' },
    { text: '模拟', link: '/mocking' },
    { text: 'Dusk (浏览器测试)', link: '/dusk' },
  ],
  packages: [
    { text: '支付 (Cashier)', link: '/billing' },
    { text: 'Cashier Paddle', link: '/cashier-paddle' },
    { text: 'Envoy', link: '/envoy' },
    { text: 'Fortify', link: '/fortify' },
    { text: 'Folio', link: '/folio' },
    { text: 'Homestead', link: '/homestead' },
    { text: 'Horizon', link: '/horizon' },
    { text: 'Octane', link: '/octane' },
    { text: 'Passport', link: '/passport' },
    { text: 'Pennant', link: '/pennant' },
    { text: 'Pint', link: '/pint' },
    { text: 'Precognition', link: '/precognition' },
    { text: 'Pulse', link: '/pulse' },
    { text: 'Reverb', link: '/reverb' },
    { text: 'Sail', link: '/sail' },
    { text: 'Sanctum', link: '/sanctum' },
    { text: 'Scout', link: '/scout' },
    { text: 'Socialite', link: '/socialite' },
    { text: 'Telescope', link: '/telescope' },
    { text: 'Valet', link: '/valet' },
  ],
  ai: [
    { text: 'AI', link: '/ai' },
    { text: 'AI SDK', link: '/ai-sdk' },
    { text: 'Boost', link: '/boost' },
    { text: 'MCP', link: '/mcp' },
  ],
}

function zhSidebarFn() {
  return [
    { text: '序言', items: zhSidebar.prologue },
    { text: '入门指南', items: zhSidebar.gettingStarted },
    { text: '架构概念', items: zhSidebar.architecture },
    { text: '基础', items: zhSidebar.basics },
    { text: '深入探索', items: zhSidebar.diggingDeeper },
    { text: '安全', items: zhSidebar.security },
    { text: '数据库', items: zhSidebar.database },
    { text: 'Eloquent ORM', items: zhSidebar.eloquent },
    { text: '测试', items: zhSidebar.testing },
    { text: '官方扩展包', items: zhSidebar.packages },
    { text: 'AI / 生态', items: zhSidebar.ai },
  ]
}

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'Laravel 文档',
  description: 'Laravel PHP Framework Documentation',

  head: [
    ['link', { rel: 'icon', href: 'https://laravel.com/img/favicon/favicon-32x32.png' }],
  ],

  cleanUrls: true,

  locales: {
    root: {
      label: 'English',
      lang: 'en-US',
      dir: 'en',
      title: 'Laravel Documentation',
      description: 'Laravel PHP Framework Documentation',
      themeConfig: {
        nav: [
          { text: 'Docs', link: '/installation' },
          {
            text: 'Ecosystem',
            items: [
              { text: 'Laravel Cloud', link: 'https://laravel.com/cloud' },
              { text: 'Forge', link: 'https://forge.laravel.com' },
              { text: 'Vapor', link: 'https://vapor.laravel.com' },
              { text: 'Nova', link: 'https://nova.laravel.com' },
              { text: 'Nightwatch', link: 'https://nightwatch.laravel.com' },
            ],
          },
          {
            text: 'Resources',
            items: [
              { text: 'Laravel News', link: 'https://laravel-news.com' },
              { text: 'Laracasts', link: 'https://laracasts.com' },
              { text: 'Bootcamp', link: 'https://bootcamp.laravel.com' },
              { text: 'Laravel Forums', link: 'https://laravel.io' },
            ],
          },
        ],
        sidebar: enSidebar(),
        socialLinks: [
          { icon: 'github', link: 'https://github.com/laravel/laravel' },
        ],
        footer: {
          message: 'Documentation for Laravel 11.x',
          copyright: 'Laravel is a trademark of Taylor Otwell. Documentation is licensed under MIT.',
        },
      },
    },
    zh: {
      label: '简体中文',
      lang: 'zh-CN',
      dir: 'zh',
      link: '/zh/',
      title: 'Laravel 中文文档',
      description: 'Laravel PHP 框架中文文档',
      themeConfig: {
        nav: [
          { text: '文档', link: '/zh/installation' },
          {
            text: '生态系统',
            items: [
              { text: 'Laravel Cloud', link: 'https://laravel.com/cloud' },
              { text: 'Forge', link: 'https://forge.laravel.com' },
              { text: 'Vapor', link: 'https://vapor.laravel.com' },
              { text: 'Nova', link: 'https://nova.laravel.com' },
              { text: 'Nightwatch', link: 'https://nightwatch.laravel.com' },
            ],
          },
          {
            text: '资源',
            items: [
              { text: 'Laravel News', link: 'https://laravel-news.com' },
              { text: 'Laracasts', link: 'https://laracasts.com' },
              { text: 'Bootcamp', link: 'https://bootcamp.laravel.com' },
              { text: 'Laravel Forums', link: 'https://laravel.io' },
            ],
          },
        ],
        sidebar: zhSidebarFn(),
        socialLinks: [
          { icon: 'github', link: 'https://github.com/laravel/laravel' },
        ],
        footer: {
          message: 'Laravel 11.x 中文文档',
          copyright: 'Laravel 是 Taylor Otwell 的商标。文档基于 MIT 许可。',
        },
      },
    },
  },
})
